---
title: "Research"
output:prettydoc::html_pretty:
    theme: cayman
    highlight: github
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

June 2013 – July 2013 &emsp; &emsp; Research Intern &emsp;&emsp;&ensp; University of Georgia &nbsp; Genome Mapping Laboratory &emsp;&emsp;&emsp;&emsp;&emsp;&nbsp; Dr. Andrew Paterson
</br>
Sept 2014 – Dec 2014 &emsp;&emsp;&nbsp; Research Intern &emsp;&emsp;&ensp; Emory &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&nbsp; Children's Center for Cystic Fibrosis &emsp;&emsp;&ensp; Dr. Tirouvanziam
</br>
January 2016 – May 2017 &ensp; Student Professional &ensp; University of Georgia &nbsp; Center for Applied Genetic Technologies &ensp; Dr. Wayne Parrott
</br>
August 2017 – May 2019 &emsp; Student Researcher &emsp; University of Georgia &nbsp; Genetics Department &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp; Dr. Jeffrey Bennetzen
</br>
August 2017 – May 2019 &emsp; Student Researcher &emsp; University of Georgia &nbsp; Biochemistry and Molecular Biology &emsp;&emsp;&nbsp; Dr. Takahiro Ito
</br>
Sept 2019 – July 2021 &emsp;&emsp;&nbsp; Research Technician &ensp;&nbsp; University of Georgia &nbsp; Crop and Soil Sciences &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp; Dr. Katrien Devos




